$(document).ready(()=>{
	console.log("Connected!");
	$('.family-login').click(()=>{
		window.location.href='youth-login-form.html';
	});
	$('.volunteer-login').click(()=>{
		window.location.href='volunteer-login-form.html';
	});
});